# Deploy Home Box from Docker Hub on Windows (Docker Desktop).
# Writes .env only (no credentials required). Enroll via http://HOST:PORT/enroll/
param(
  [string]$Tag = $(if ($env:HOME_BOX_TAG) { $env:HOME_BOX_TAG } else { "latest" }),
  [int]$Port = $(if ($env:HOME_BOX_HTTP_PORT) { [int]$env:HOME_BOX_HTTP_PORT } else { 8123 }),
  [string]$Data = $(if ($env:HOME_BOX_DATA) { $env:HOME_BOX_DATA } else { ".\data" }),
  [string]$TimeZone = $(if ($env:TZ) { $env:TZ } else { "UTC" }),
  [ValidateSet("0", "1")]
  [string]$EnableLanSocks = $(if ($env:ENABLE_LAN_SOCKS) { $env:ENABLE_LAN_SOCKS } else { "1" })
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

New-Item -ItemType Directory -Force -Path (Join-Path $Data "config\wireguard") | Out-Null

$secretsPath = Join-Path $Data "config\secrets.yaml"
if (-not (Test-Path $secretsPath)) {
  $hostName = $env:COMPUTERNAME
  if (-not $hostName) { $hostName = "homeassistant.local" }
  @"
# Generated by deploy.ps1 — no tokens. Edit URLs for this box.
ha_external_url: http://${hostName}:${Port}
ha_internal_url: http://${hostName}:${Port}
"@ | Set-Content -Path $secretsPath -Encoding utf8
  Write-Host "Seeded $secretsPath (placeholder URLs only; no tokens)"
}

@"
TZ=$TimeZone
HOME_BOX_HTTP_PORT=$Port
HOME_BOX_DATA=$Data
HOME_BOX_TAG=$Tag
ENABLE_LAN_SOCKS=$EnableLanSocks
"@ | Set-Content -Path .env -Encoding utf8

Write-Host "Wrote $PWD\.env"
Write-Host "  TZ=$TimeZone"
Write-Host "  HOME_BOX_HTTP_PORT=$Port"
Write-Host "  HOME_BOX_DATA=$Data"
Write-Host "  HOME_BOX_TAG=$Tag"
Write-Host "  ENABLE_LAN_SOCKS=$EnableLanSocks"

if ($EnableLanSocks -eq "1") {
  Write-Host "Windows lab: start .\tuya\socks5-windows.ps1 from the repo (or copy) so LAN devices work."
}

docker compose -f compose.yaml pull
docker compose -f compose.yaml up -d

Write-Host ""
Write-Host "Home Box is starting."
Write-Host "  UI:     http://localhost:${Port}/"
Write-Host "  Enroll: http://localhost:${Port}/enroll/"
Write-Host "No BMS tokens in .env — scan the prepare-box QR on Enroll."
